# settings.yaml

simulation:
  target_fps: 2
  simulation_speed: 1.0
  total_duration: 3  # 仿真总时长（秒）

environment:
  map_width: 200      #整数，-100到+100
  map_height: 200

population:
  initial_rabbits: 10
  initial_wolves: 3

rabbit:
  # === 兔子 (被捕食者) ===
  # 特点: 繁殖快，生命周期短，擅长侦查和逃跑
  # 固定属性
  UL_life_time: 300.0           # 最大寿命 (秒)
  LL_life_time: 30.0            # 最小寿命
  UL_hunger: 100.0              # 最大饱腹度
  UL_energy: 100.0              # 最大能量
  birth_max_hunger: 30.0        # 出生时最大饱腹度
  birth_max_energy: 40.0        # 出生时最大能量
  UL_speed: 15.0                # 速度上限
  LL_speed: 1.0                 # 速度下限
  birth_value: 15.0             # 出生时的食用价值
  hunger_consume_rate: 1.5      # 饥饿速度 (需要更频繁吃草)
  energy_consume_rate: 1.0      # 疲劳速度
  energy_recovery_rate: 4.0     # 能量回复速度
  # 初始遗传属性
  init_reproduce_age: 40.0      # 成年年龄 (更快成年)
  init_hunger_desire: 0.7       # 饥饿阈值 (更积极觅食)
  init_energy_desire: 0.6       # 能量阈值
  init_life_time: 180.0         # 平均寿命
  init_vision_range: 20.0       # 视野范围
  init_search_range: 40.0       # 搜寻范围
  init_standard_speed: 8.0      # 标准移动速度 (低于速度上限)
  init_standard_value: 30.0     # 被捕食的营养价值
  init_reproduction_cooldown_time: 30 # 繁殖冷却 (繁殖更频繁)
  init_offspring_amount: 4      # 每胎数量 (更多后代)
  init_givebirth_sex_bias: 0.5  # 性别偏好
  init_flee_factor: 2.0         # 逃跑因子 (跑得更远)
  init_flee_speed_factor: 1.8   # 逃跑时速度变增加的倍数，但不能超过上限
  init_pregant_dur: 20.0        # 怀孕时长

wolf:
  # === 狼 (捕食者) ===
  # 特点: 繁殖慢，生命周期长，擅长追踪和捕猎
  # 固定属性
  UL_life_time: 600.0           # 最大寿命 (秒)
  LL_life_time: 60.0            # 最小寿命
  UL_hunger: 100.0              # 最大饱腹度
  UL_energy: 120.0              # 最大能量 (耐力更强)
  birth_max_hunger: 40.0        # 出生时最大饱腹度
  birth_max_energy: 40.0        # 出生时最大能量
  UL_speed: 12.0                # 速度上限
  LL_speed: 2.0                 # 速度下限
  birth_value: 20.0             # 出生时的食用价值 (对于可能的更高级捕食者)
  hunger_consume_rate: 1.0      # 饥饿速度 (一次吃饱, 消耗更慢)
  energy_consume_rate: 1.5      # 疲劳速度 (追猎时消耗更大)
  energy_recovery_rate: 3.0     # 能量回复速度
  # 初始遗传属性
  init_reproduce_age: 100.0     # 成年年龄 (更慢成年)
  init_hunger_desire: 0.5       # 饥饿阈值 (不那么容易饿)
  init_energy_desire: 0.5       # 能量阈值
  init_life_time: 400.0         # 平均寿命
  init_vision_range: 40.0       # 视野范围
  init_search_range: 80.0       # 搜寻范围 
  init_standard_speed: 10.0     # 标准移动速度 (比兔子标准速度快，用于追捕)
  init_standard_value: 80.0     # 被捕食的营养价值
  init_reproduction_cooldown_time: 150 # 繁殖冷却 (繁殖频率低)
  init_offspring_amount: 2      # 每胎数量 (更少后代)
  init_givebirth_sex_bias: 0.5  # 性别偏好
  init_flee_factor: 1.0         # 逃跑因子
  init_flee_speed_factor: 1.8   # 逃跑时速度变增加的倍数，但不能超过上限
  init_pregant_dur: 60.0        # 怀孕时长

grass:
  currentvalue: 30.0
  max_amount: 300
  refresh_interval: 10.0  #刷新草的时间间隔
  grow_amount_per_refresh: 2   #每次刷新长出几个草。因为草是整数，必须要通过判断时间到达后长出整数个的方式长草。

